stages:
  - java-badges

java-badges:
  image: maven:latest
  stage: java-badges
  cache:
    paths:
      - target/
  before_script:
    # install readme-badges
    - git clone https://github.com/InternetGuru/readme-badges
    - |
        if ! git -C readme-badges checkout -q "$RB_REVISION"; then
          revision="$(git -C readme-badges tag | grep ^v$RB_REVISION\. | sort --version-sort | tail -1)"
          git -C readme-badges checkout "$revision"
        fi
    # set permissions
    - chmod +x readme-badges/java-badges.sh
  script:
    - ./readme-badges/java-badges.sh
  artifacts:
    paths:
      - .results/
    expire_in: 1 year
